number = float(input("Digite um número.: "))
dnumber = float(number*2)
tnumber = float(number*3)
raiznumber = float(number**(1/2))
raiznumber2 = float(pow(number, 1/2))
print("Para o número.: {}".format(number))
print("O dobro.: {}".format(dnumber))
print("O triplo.: {}".format(tnumber))
print("A sua raiz quadrada é.: {:.2f}".format(raiznumber))
print("A sua raiz quadrada é.: {:.2f}".format(raiznumber2))